export const cmsPreviewCopy = {
  incompleteSection: "Seção incompleta",
  incompleteHeader: "Cabeçalho incompleto",
  missingPrefix: "falta",
  separator: ", ",
  and: " e ",
  genericMissing: "conteúdo obrigatório",
  fieldLabels: {
    title: "o título",
    subtitle: "o subtítulo",
    intro: "a introdução",
    body: "o corpo",
    cards: "os cartões",
    quotes: "os depoimentos",
    people: "as pessoas",
    image: "a imagem",
    count: "a quantidade",
    videoUrl: "o link do vídeo",
    videoTitle: "o título do vídeo",
    ctaLabel: "o texto do botão",
    caption: "a legenda",
    _type: "o tipo",
  },
} as const
