name: Prevent Supabase Inactivity

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight every Sunday
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping-databases:
    runs-on: ubuntu-latest
    env:
      STAGING_SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
      STAGING_SUPABASE_ANON_KEY: ${{ secrets.STAGING_SUPABASE_ANON_KEY }}
      PRODUCTION_SUPABASE_URL: ${{ secrets.PRODUCTION_SUPABASE_URL }}
      PRODUCTION_SUPABASE_ANON_KEY: ${{ secrets.PRODUCTION_SUPABASE_ANON_KEY }}
    steps:
      - name: Make an API request to Staging Supabase
        run: |
          curl -X GET "${{ env.STAGING_SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ env.STAGING_SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ env.STAGING_SUPABASE_ANON_KEY }}"

      - name: Make an API request to Production Supabase
        run: |
          curl -X GET "${{ env.PRODUCTION_SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ env.PRODUCTION_SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ env.PRODUCTION_SUPABASE_ANON_KEY }}"